FROM ubuntu:16.04 
MAINTAINER "swz"

#设置代理网络
ENV http_proxy http://10.1.27.102:8080

#RUN echo -e "\nexport http_proxy=http://10.1.27.102:8080 \nexport https_proxy=http://10.1.27.102:8080" >> ~/.bashrc
#RUN echo "Acquire::http::proxy \"http://10.1.27.102:8080\";" >> /etc/apt/apt.conf
#RUN echo "Acquire::https::proxy \"http://10.1.27.102:8080\";" >> /etc/apt/apt.conf

#apt-get 换源
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt-get update

#安装linux基本软件
RUN apt-get install -y vim curl net-tools bash-completion --fix-missing

#安装nodejs
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs --fix-missing
RUN ln -s /usr/bin/nodejs /usr/bin/node

#安装npm、git并设置代理
RUN apt-get install -y npm --fix-missing
RUN npm config set https-proxy http://10.1.27.102:8080
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN apt-get install -y git --fix-missing
RUN git config --global http.proxy 10.1.27.102:8080

#安装vue-cli
RUN npm install -y --global vue-cli

#安装nginx
RUN apt-get install -y nginx --fix-missing

#开放Vue-Cli、nginx端口
EXPOSE 8080
EXPOSE 80

ENV http_proxy ""
